Repository JourneyPlanner/JourneyPlanner, pull requests merged in 2025-02, with the labels that each got.

#501 fix: update user after closing user settings (fixes #430) & throw error when journey not accessable (fixes #427)
  frontend/error.vue
  frontend/pages/dashboard.vue
  frontend/pages/journey/[id].vue
  frontend/pages/user/[username].vue
Labels: fix

#543 refactor: update uppy packages
  frontend/components/dashboard/UserSettings.vue
  frontend/components/journey/id/Upload.vue
  frontend/components/settings/DeleteAccount.vue
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies, frontend

#527 feat: JP-19: Edit/delete templates
  backend/app/Http/Controllers/Journey/JourneyController.php
  backend/app/Http/Controllers/Journey/TemplateController.php
  backend/app/Http/Requests/Journey/UpdateTemplateRequest.php
  backend/app/Models/Journey.php
  backend/app/Policies/JourneyPolicy.php
  backend/routes/api.php
  frontend/components/journey/id/MenuSidebar.vue
  frontend/components/journey/id/TicketSection.vue
  frontend/components/journey/id/dialogs/CreateTemplateDialog.vue
  frontend/components/template/Card.vue
  frontend/components/template/CardSmall.vue
  frontend/components/template/Popup.vue
  frontend/pages/dashboard.vue
  frontend/pages/journey/[id].vue
  frontend/pages/template/[id]/edit.vue
  frontend/pages/template/[id]/index.vue
  frontend/pages/user/[username].vue
  frontend/stores/journey.js
  frontend/stores/template-filter.js
  frontend/stores/templates.js
Labels: feat

#528 JP-153: feat: Kick from journey
  backend/app/Http/Controllers/Journey/JourneyUserController.php
  backend/routes/api.php
  frontend/components/journey/id/MemberSidebar.vue
  frontend/components/journey/id/components/MemberItem.vue
  frontend/components/journey/id/components/confirm/KickMember.vue
  frontend/package-lock.json
  frontend/pages/journey/[id].vue
Labels: feat

#554 feat: JP-49 demo subdomain
  backend/app/Http/Controllers/BusinessController.php
  backend/app/Http/Controllers/Journey/TemplateController.php
  backend/app/Models/Business/Business.php
  backend/app/Models/Business/BusinessImage.php
  backend/app/Models/Business/BusinessImageAltText.php
  backend/app/Models/Business/BusinessText.php
  backend/database/migrations/2025_02_08_084533_create_businesses_table.php
  backend/database/migrations/2025_02_08_084546_create_business_images_table.php
  backend/database/migrations/2025_02_08_084559_create_business_texts_table.php
  backend/database/migrations/2025_02_08_084614_create_business_activities_table.php
  backend/database/migrations/2025_02_08_084629_create_business_templates_table.php
  backend/database/migrations/2025_02_08_094635_create_business_users_table.php
  backend/database/migrations/2025_02_08_094837_create_business_image_alt_texts_table.php
  backend/routes/api.php
  frontend/components/business/ActivityCard.vue
  frontend/components/journey/id/dialogs/ActivityDialog.vue
  frontend/components/template/Card.vue
  frontend/composables/useInfiniteScrolling.ts
  frontend/pages/business/[slug].vue
  frontend/pages/journey/[id].vue
Labels: feat

#556 feat: JP-25 rate templates
  backend/app/Http/Controllers/Journey/TemplateController.php
  backend/app/Http/Controllers/Journey/TemplateRatingController.php
  backend/app/Models/Journey.php
  backend/app/Models/TemplateRating.php
  backend/database/migrations/2025_01_29_115301_template_ratings.php
  backend/routes/api.php
  frontend/components/template/Card.vue
  frontend/components/template/CardSmall.vue
  frontend/components/template/Popup.vue
  frontend/nuxt.config.ts
  frontend/pages/dashboard.vue
  frontend/stores/template-filter.js
  frontend/stores/templates.js
  frontend/types/index.d.ts
Labels: feat

#563 JP-203: fix: guest mode bug - only request /me/template if authenticated
  frontend/pages/journey/[id].vue
Labels: fix

#562 JP-205: fix: darkmode colors for header links now match with the colo…
  frontend/pages/about.vue
Labels: fix

#506 fix: always show edit/delete buttons in activity dialog
  frontend/components/form/CalendarRange.vue
  frontend/components/form/CalendarSelect.vue
  frontend/components/journey/EditDialog.vue
  frontend/components/journey/id/components/ActivityPool.vue
  frontend/pages/invite/[id].vue
  frontend/pages/journey/new/index.vue
  frontend/pages/journey/new/template/[templateid].vue
Labels: fix
